version: "3"
services:
  cloudflared:
    build: cloudflared
    networks:
      test:
        ipv4_address: 172.28.1.2
  host:
    image: debian
    command: sleep infinity
    networks:
      test:
        ipv4_address: 172.28.1.3
  pihole:
    image: diginc/pi-hole
    networks:
      test:
        ipv4_address: 172.28.1.4
    ports:
      - "9999:53/tcp"
      - "9999:53/udp"
#      - "8443:443/tcp"
      - "8080:80/tcp"
    environment:
      # enter your docker host IP here
      ServerIP: "0.0.0.0"
      DNS1: "172.28.1.2"
      DNS2: "no"
      WEBPASSWORD: "p3i1t4N1"
      DNSMASQ_LISTENING: "all"
    # Add your own custom hostnames you need for your domain
    #volumes:
    #  - "./pihole:/etc/pihole"
    #  - "./dnsmasq.d:/etc/dnsmasq.d"
    #  - "./log/pihole.log:/var/log/pihole.log"
    #restart: always
  dnss:
    build: dnss
    networks:
      test:
        ipv4_address: 172.28.1.5
#    ports:
#      - "443:443/tcp"
#      - "443:443/udp"
networks:
  test:
    driver: overlay
    ipam:
     config:
       - subnet: 172.28.0.0/16
