version: "3"
services:
  deb_test:
    image: debian
    command: ["sleep", "infinity"]
    networks:
      test:
        ipv4_address: 172.28.1.23
  cloudflared:
    build: cloudflared
    networks:
      test:
        ipv4_address: 172.28.1.2
  pihole:
    image: diginc/pi-hole
    networks:
      test:
        ipv4_address: 172.28.1.4
    environment:
      # enter your docker host IP here
      ServerIP: "0.0.0.0"
      DNS1: "172.28.1.2"
      DNS2: "no"
      WEBPASSWORD: "p3i1t4N1"
      DNSMASQ_LISTENING: "all"
    # Add your own custom hostnames you need for your domain
    #volumes:
    #  - "./pihole:/etc/pihole"
    #  - "./dnsmasq.d:/etc/dnsmasq.d"
    #  - "./log/pihole.log:/var/log/pihole.log"
    #restart: always
  dnss:
    build: dnss
    networks:
      test:
        ipv4_address: 172.28.1.5
  caddy:
    build: caddy
    volumes:
      - caddy-data:/root/.caddy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "853:853/udp"
    networks:
      test:
        ipv4_address: 172.28.1.6

volumes:
  caddy-data:

networks:
  test:
    driver: overlay
    ipam:
     config:
       - subnet: 172.28.0.0/16
