version: "3"
services:
  cloudflared:
    restart: always
    build: cloudflared
    networks:
      test:
        ipv4_address: 172.28.1.2
  pihole:
    restart: always
    image: diginc/pi-hole
    networks:
      test:
        ipv4_address: 172.28.1.4
    environment:
      ServerIP: "0.0.0.0"
      DNS1: "172.28.1.2"
      DNS2: "no"
      DNSMASQ_LISTENING: "all"
    volumes:
      - pihole-etc-pihole:/etc/pihole
      - pihole-dnsmasqd:/etc/dnsmasq.d
      - pihole-log:/var/log/
  caddy:
    restart: always
    environment:
      - ERISEDHOST
      - ERISEDEMAIL
    build: caddy
    volumes:
      - caddy-data:/root/.caddy
    ports:
      - "80:80/tcp"
      - "853:853/tcp"
      - "853:853/udp"
    networks:
      test:
        ipv4_address: 172.28.1.6

volumes:
  caddy-data:
  pihole-etc-pihole:
  pihole-dnsmasqd:
  pihole-log:

networks:
  test:
    driver: overlay
    ipam:
     config:
       - subnet: 172.28.0.0/16